# Project: 项目2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 项目2_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"E:/Coding/IDEs/Dev-Cpp/MinGW64/lib" -L"E:/Coding/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"E:/Coding/IDEs/Dev-Cpp/MinGW64/include" -I"E:/Coding/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Coding/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Coding/IDEs/Dev-Cpp/MinGW64/include" -I"E:/Coding/IDEs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Coding/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Coding/IDEs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目2.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

项目2_private.res: 项目2_private.rc icon.rc
	$(WINDRES) -i 项目2_private.rc --input-format=rc -o 项目2_private.res -O coff 

